# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.takewithme.com
title: Take with me
author: Shaozhuang Liu
simple_search:
description:

date_format: "%Y %B %e : %H:%M %Z"

category_title_prefix: ""

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
category_feeds: false
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: tag
markdown: rdiscount
pygments: false # Jekyll's default Python Pygments have been replaced by pygments.rb. Set to true to use Albino + Pythong Pygments

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_in_feed: false # Truncate excerpted articles in the atom feed
permalink_label: "Permalink"
permalink_label_feed: "&#9875; Permalink"
linklog_marker: "&rarr;"
linklog_marker_position: after
linklog_marker_position_feed: after
standard_post_marker:

titlecase: false       # Converts page and post titles to titlecase

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html
blog_index_sidebar: page_default.html
page_sidebar: page_default.html
post_sidebar: page_default.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Javascript social buttons often generate lots of http requests and may track your viewer's browsing history
# Show respect for privacy and bandwidth with simple links for Twitter, Facebook and Google Plus.
respectfully_social: true

# Github repositories
github_user: stliu
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true

# Twitter
# twitter_user: strongliu
# twitter_tweet_count: 3
# twitter_show_replies: false
# twitter_follow_button: true
# twitter_show_follower_count: true
# twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_user:
google_plus_hidden: false
google_plus_image_size: 32

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: takewithme
disqus_show_comment_count: false
disqus_developer: 0

# Facebook Like
facebook_like: false
google_analytics_tracking_id: UA-4998948-1
